### ISSUE TITLE
Pie chart label connectors look bad.

### ISSUE THREAD

**Issue by Peppe** [vaadin/vaadin-charts#295]
The label connectors in pie charts, and possibly other chart types, look bad in Charts 6.
![charts6-pie-labels](https://user-images.githubusercontent.com/525503/36944856-df2b54ae-1fac-11e8-8afe-39bc6c7afacd.png)

The connectors have both a stroke and fill, when they should have only a stroke and no fill. In vaadin-chart-default-theme.html#L825 there are all the colors that define strokes and fills for all colors, which are correct:
```css
.highcharts-color-0 {
  fill: var(--vaadin-charts-color-0, #7cb5ec);
  stroke: var(--vaadin-charts-color-0, #7cb5ec);
}
```

There is also a rule to remove the stroke when it is rendering label connectors, chart-default-theme.html#L298:
```css
.highcharts-data-label-connector {
  fill: none;
}
```

The problem is that the colors are defined **after** the special rules for data label connectors, and thus the colored stroke gets priority. To fix the issue, move the copy snippet avove in line #L298 to after the color specifications, to #L874.
